services:
  server:
    build: 'dev.dockerfile'
    environment:
      - PORT=${PORT}
      - DISCORD_SECRET=${DISCORD_SECRET}
    restart: unless-stopped
    depends_on:
      - translate

  translate:
    image: libretranslate/libretranslate
    restart: unless-stopped
