services:
  server:
    build: 'dev.dockerfile'
    environment:
      - PORT=${PORT}
      - DISCORD_SECRET=${DISCORD_SECRET}
      - NODE_ENV=development
      - TRANSLATE_URL=translate
      - TRANSLATE_PORT=5000
    restart: unless-stopped
    depends_on:
      - translate

  translate:
    image: libretranslate/libretranslate
    restart: unless-stopped
