services:
  server:
    build:
      context: .
      dockerfile: ./dev.dockerfile
    environment:
      - PORT=${PORT}
      - DISCORD_SECRET=${DISCORD_SECRET}
      - NODE_ENV=development
      - TRANSLATE_URL=translate
      - TRANSLATE_PORT=5000
    restart: unless-stopped
    depends_on:
      - translate
    ports:
      - ${PORT}:${PORT}
    volumes:
      - ./:/app
      - /app/node_modules

  translate:
    image: libretranslate/libretranslate
    restart: unless-stopped
    ports:
      - 5000:5000
    volumes:
      - /
