services:
  server:
    build: '.'
    environment:
      - PORT=#{PORT}
      - DISCORD_SECRET=${DISCORD_SECRET}
    restart: unless-stopped
    depends_on:
      - translate
    volumes:
      - ./logs/server:/app/logs

  translate:
    image: libretranslate/libretranslate
    restart: unless-stopped
