services:
  server:
    build: '.'
    environment:
      - PORT=${PORT}
      - DISCORD_SECRET=${DISCORD_SECRET}
      - NODE_ENV=production
      - TRANSLATE_URL=translate
      - TRANSLATE_PORT=5000
    restart: unless-stopped
    depends_on:
      - translate
    volumes:
      - ./logs/server:/app/logs
    ports:
      - ${PORT}:${PORT}

  translate:
    image: libretranslate/libretranslate
    restart: unless-stopped
